import type { NextPage } from "next";
import Head from "next/head";
import HomeScreen from "./Home";

const Home: NextPage = () => {
  return (
    <div>
      {typeof window !== "undefined" ? (
        <div>
          <Head>
            <title>Buy Me a Java</title>
            <meta name="description" content="Generated by Buy me a java" />
            <link rel="icon" href="/favicon.ico" />
            <script src="https://www.paypal.com/sdk/js?client-id=AXhg67os1Hi3QkcZED-_fcnVaR858kMaLOmA0DaGE6HP4mm0PBwRDhIv6Q65sJgg1mlrv_aDu3j8Mg9z&currency=USD"></script>
          </Head>

          <HomeScreen />
        </div>
      ) : null}
    </div>
  );
};

export default Home;
