import { Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Buy me a java</title>
        <meta name="description" content="Generated by Buy me a java" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Text>heeeyyyyyyyyyy</Text>
    </div>
  );
};

export default Home;
